/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCol: typeof import('@nutui/nutui')['Col']
    NutRow: typeof import('@nutui/nutui')['Row']
    NutSkeleton: typeof import('@nutui/nutui')['Skeleton']
  }
}
